baseurl = "http://www.samudranb.com/"
canonifyurls = true
disqusShortname = "samudranb"
googleAnalytics = "UA-85626859-1"
languageCode = "en-US"
paginate = 6
theme = "casper-two"
title = "Samudra's thoughts on"
[[menu.main]]
name = "Home"
url = "/post/"
weight = 1
[params]
RSSLink = ""
author = "Samudra"
authorAvatar = "img/snb_icon.png"
authorDescription = "An instantiating being."
authorLocation = "Earth, for now."
authorWebsite = "https://samudranb.github.io"
copyright = "© 2018"
cover = "img/blog-cover.jpg"
customCSS = []
description = "About instantiating and being a being"
githubName = "samudranb"
linkedinName = "samudra"
mediumName = "samudranb"
metaDescription = "Thoughts from Samudra"
pageNotFoundTitle = "404 - Page not found"
showSupport = true
singleViewStyle = "casper"
subtitle = "Being Instantiating."
title = "Samudra Neelam Bhuyan"
twitterName = "samudranb"
[permalinks]
post = "/post/:slug/"
